import { SourceDialog } from "../components/SourceDialog";
import { useEffect, useState } from "react";
import { BookOpen, RefreshCw, Search } from "lucide-react";
import { knowledge, type Coverage, type EmbeddingConfig, type KnowledgeHit, type Preparation, type PreparationKind, type ProjectMemory } from "../lib/knowledge";
import { scanProject, type ProjectRecord } from "../lib/ipc";
import type { EvidenceRef } from "../lib/types";
import { AnswerMarkdown } from "../overlay/AnswerMarkdown";
import { FileUpload } from "../context/FileUpload";
import { useContextStore } from "../stores/contextStore";

const button = "inline-flex items-center justify-center gap-2 border border-border px-3 py-2 text-xs hover:bg-accent disabled:opacity-50";
const field = "w-full border border-border bg-background px-3 py-2 text-sm";
const labels: Record<PreparationKind, string> = { return: "What changed?", rehearsal: "Meeting rehearsal", handbook: "Project handbook" };

export function ProjectWorkspace({ project, onChanged }: { project?: ProjectRecord; onChanged: () => void }) {
  const [coverage, setCoverage] = useState<Coverage | null>(null);
  const [config, setConfig] = useState<EmbeddingConfig>();
  const [memory, setMemory] = useState<ProjectMemory>({ questions: [], decisions: [] });
  const [kind, setKind] = useState<PreparationKind>("return");
  const [prep, setPrep] = useState<Preparation | null>(null);
  const [busy, setBusy] = useState("");
  const [error, setError] = useState("");
  const [query, setQuery] = useState("");
  const [hits, setHits] = useState<KnowledgeHit[]>([]);
  const [searched, setSearched] = useState(false);
  const [decision, setDecision] = useState("");
  const [draftNotice, setDraftNotice] = useState("");
  const [selectedSources, setSelectedSources] = useState<string[]>([]);
  const [source, setSource] = useState<{ ref: EvidenceRef; text: string }>();
  const [linked, setLinked] = useState<string[]>([]);
  const resources = useContextStore(s => s.resources);
  const loadResources = useContextStore(s => s.loadResources);
  const id = project?.id;

  const refresh = async () => {
    if (!id) return;
    const [c, cfg, m, docs] = await Promise.all([knowledge.coverage(id).catch(() => null), knowledge.config(id), knowledge.memory(id), knowledge.documents(id)]);
    setCoverage(c); setConfig(cfg); setMemory(m); setLinked(docs);
  };
  useEffect(() => { let active = true; setCoverage(null); setPrep(null); setHits([]); setSearched(false); setError(""); setSource(undefined); setSelectedSources([]); setDraftNotice("");
    if (id) Promise.all([knowledge.coverage(id).catch(() => null), knowledge.config(id), knowledge.memory(id), knowledge.documents(id)]).then(([c, cfg, m, docs]) => { if (active) { setCoverage(c); setConfig(cfg); setMemory(m); setLinked(docs); } }).catch(e => { if (active) setError(String(e)); });
    loadResources(); return () => { active = false; };
  }, [id, loadResources]);
  useEffect(() => { let active = true; setPrep(null); if (id) knowledge.preparation(id, kind).then(p => { if (active) setPrep(p); }).catch(e => { if (active) setError(String(e)); }); return () => { active = false; }; }, [id, kind]);
  const run = async (label: string, action: () => Promise<unknown>) => { setBusy(label); setError(""); try { await action(); } catch (e) { setError(String(e)); } finally { setBusy(""); } };
  const openSource = (ref: EvidenceRef) => run("Opening source", async () => setSource({ ref, text: await knowledge.source(ref.id) }));
  const refs = (evidence: EvidenceRef[]) => <div className="mt-2 flex flex-col items-start gap-1">{evidence.map((ref, i) => <button key={ref.id} className="text-left text-xs text-primary break-all hover:underline" onClick={() => openSource(ref)}>[S{i + 1}] {ref.path}:{ref.startLine}–{ref.endLine}</button>)}</div>;

  if (!project) return <div className="m-auto max-w-md px-6 py-12"><BookOpen size={24} className="mb-5 text-primary" /><h1 className="text-xl font-medium">Get to know your project</h1><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Choose a project from the sidebar, or add its repository folder. Search the original code, prepare for questions, and keep reviewed decisions together.</p><p className="mt-3 text-xs text-muted-foreground">Only folders you select are indexed.</p></div>;
  return <div className="min-h-0 flex-1 overflow-y-auto p-4 lg:p-6 space-y-6" aria-label="Project preparation">
    <header><p className="text-xs text-muted-foreground">PROJECT PREPARATION</p><h1 className="mt-1 text-xl font-medium break-words">{project.name}</h1><p className="mt-1 text-xs text-muted-foreground break-all">{project.root_path}</p></header>
    {error && <p role="alert" className="border-l-2 border-destructive bg-destructive/5 p-3 text-sm text-destructive">{error}</p>}
    {busy && <p role="status" className="flex items-center gap-2 text-xs text-primary"><RefreshCw size={14} className="animate-spin" />{busy}…</p>}
    <section className="border-y border-border py-3 space-y-3" aria-label="Index coverage">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-medium">{coverage ? "Source index available" : "Build your source index"}</h2><p className="mt-1 text-xs text-muted-foreground">{coverage ? `${coverage.indexedFiles} files · ${coverage.chunks} passages · ${coverage.excluded.length} excluded` : "Code, documentation and GitHub workflows. A failed update keeps the previous index."}</p>{coverage && <p className="mt-1 text-xs text-muted-foreground">Snapshot {coverage.revision.slice(0, 10)} · {new Date(coverage.scannedAt).toLocaleString()} · {coverage.searchMode.startsWith("hybrid") ? "Hybrid index" : "Keyword index"}</p>}</div>
        <button className={button} disabled={!!busy} onClick={() => run("Updating source index", async () => { await scanProject(project.id); await refresh(); onChanged(); })}><RefreshCw size={13} />Update index</button></div>
      {coverage?.freshness && <p role="status" className={`text-xs ${coverage.freshness === "current" ? "text-muted-foreground" : "text-amber-600 dark:text-amber-400"}`}>{coverage.freshness === "current" ? "Matches local sources at the last check." : coverage.freshness === "stale" ? "Local sources changed. Answers use the saved snapshot until you update the index." : "Local sources could not be checked. The last saved snapshot remains available."}</p>}
      {coverage && <details><summary className="text-xs cursor-pointer">Coverage & excluded files</summary><p className="my-2 text-xs text-muted-foreground">{coverage.gitAware ? "Git tracked and untracked files, respecting ignore rules." : "Folder scan; no Git revision available."} {coverage.reusedFiles} unchanged files reused. The snapshot does not prove deployment status.</p><ul className="max-h-40 overflow-auto space-y-1 text-xs">{coverage.excluded.map((x, i) => <li key={i} className="break-all"><span className="font-mono">{x.path}</span> · {x.reason}</li>)}</ul></details>}
      <details><summary className="text-xs cursor-pointer">Search provider</summary>{config && <div className="mt-3 space-y-3"><label className="block text-xs">Embedding provider<select aria-label="Embedding provider" className={`${field} mt-1`} value={config.provider} onChange={e => { const provider = e.target.value as EmbeddingConfig["provider"]; setConfig({ ...config, provider, model: provider === "gemini" ? "gemini-embedding-2" : provider === "ollama" ? "nomic-embed-text" : config.model, dimensions: provider === "ollama" ? 768 : 1536 }); }}><option value="lexical">Keyword search only</option><option value="gemini">Gemini embedding 2 · cloud</option><option value="ollama">Ollama · local</option></select></label>
        {config.provider === "ollama" && <div className="space-y-2"><label className="block text-xs">Endpoint<input className={field} value={config.baseUrl} onChange={e => setConfig({ ...config, baseUrl: e.target.value })} /></label><label className="block text-xs">Model<input className={field} value={config.model} onChange={e => setConfig({ ...config, model: e.target.value })} /></label><label className="block text-xs">Dimensions<input className={field} type="number" value={config.dimensions} onChange={e => setConfig({ ...config, dimensions: Number(e.target.value) })} /></label></div>}
        <p className="text-xs text-muted-foreground">{config.provider === "gemini" ? "Uses the Gemini key in settings. Indexing sends selected project passages to this API." : "Keyword search stays available if embeddings fail."}</p><button className={button} disabled={!!busy} onClick={() => run("Saving search configuration", async () => { await knowledge.config(project.id, config); if (config.provider !== "lexical") { setBusy("Embedding source passages"); await knowledge.embed(project.id); } await refresh(); })}>{config.provider === "lexical" ? "Save search preference" : "Save & build semantic index"}</button></div>}</details>
    </section>
    <section><h2 className="text-sm font-medium">Find an answer in the sources</h2><form className="mt-3 flex gap-2" onSubmit={e => { e.preventDefault(); run("Searching project", async () => { setHits(await knowledge.search(project.id, query)); setSearched(true); setSelectedSources([]); }); }}><input aria-label="Search project sources" className={`${field} min-w-0`} value={query} onChange={e => setQuery(e.target.value)} placeholder="How does the document pipeline work?" /><button aria-label="Search sources" className={button} disabled={!!busy || !query.trim()}><Search size={16} /></button></form>
      {searched && !hits.length && <p className="mt-3 text-sm text-muted-foreground">No matching sources. Try a file name, symbol or a more specific question.</p>}
      {hits.length > 0 && <div className="mt-3 divide-y divide-border">{hits.map(hit => <div className="py-3" key={hit.evidence.id}><div className="flex gap-2 items-start"><input type="checkbox" aria-label={`Attach ${hit.evidence.path} to decision`} checked={selectedSources.includes(hit.evidence.id)} onChange={e => setSelectedSources(old => e.target.checked ? [...old, hit.evidence.id] : old.filter(x => x !== hit.evidence.id))} /><button className="text-xs text-primary text-left break-all" onClick={() => openSource(hit.evidence)}>{hit.evidence.path}:{hit.evidence.startLine}–{hit.evidence.endLine}</button></div><p className="mt-2 line-clamp-3 whitespace-pre-wrap text-xs text-muted-foreground">{hit.text}</p></div>)}</div>}
      {query.trim() && <button className={`${button} mt-3`} disabled={!!busy} onClick={() => run("Saving open question", async () => { await knowledge.saveQuestion(project.id, query); await refresh(); })}>Keep as open question</button>}
      {selectedSources.length > 0 && <div className="mt-4 space-y-2"><label className="block text-xs">Decision draft · {selectedSources.length} source(s)<textarea className={`${field} mt-1`} rows={3} value={decision} onChange={e => setDecision(e.target.value)} placeholder="What was decided, by whom and when?" /></label><button className={button} disabled={!!busy || !decision.trim()} onClick={() => run("Saving decision draft", async () => { await knowledge.updateMemory(project.id, { kind: "decision", text: decision, evidence: hits.filter(h => selectedSources.includes(h.evidence.id)).map(h => h.evidence) }); setDecision(""); setSelectedSources([]); await refresh(); })}>Save for review</button></div>}
    </section>
    <section className="border-t border-border pt-4"><div className="flex flex-wrap gap-1" role="tablist" aria-label="Preparation format">{(Object.keys(labels) as PreparationKind[]).map(k => <button key={k} role="tab" aria-selected={kind === k} className={`${button} ${kind === k ? "bg-accent text-foreground" : "text-muted-foreground"}`} onClick={() => setKind(k)}>{labels[k]}</button>)}</div>
      <div role="tabpanel" className="mt-4">{prep ? <><p className="mb-3 text-xs text-muted-foreground">Generated {new Date(prep.createdAt).toLocaleString()} · source snapshot {prep.revision.slice(0, 10)} · review before use</p><AnswerMarkdown content={prep.text} /><details className="mt-3"><summary className="text-xs cursor-pointer">Original sources</summary>{refs(prep.evidence)}</details></> : <p className="text-sm text-muted-foreground">{kind === "return" ? "Catch up on repository changes since your last recorded meeting, plus reviewed decisions." : kind === "rehearsal" ? "Practice likely questions with short, sourced answers and clear knowledge gaps." : "A source-based guide to the architecture, vocabulary and important flows."}</p>}<button className={`${button} mt-4`} disabled={!!busy || !coverage} onClick={() => run(`Preparing ${labels[kind].toLowerCase()}`, async () => setPrep(await knowledge.preparation(project.id, kind, true)))}>{prep ? "Regenerate" : "Generate"}</button></div>
    </section>
    <section className="border-t border-border pt-4"><div className="flex flex-wrap justify-between gap-2"><h2 className="text-sm font-medium">Open questions · {memory.questions.filter(q => q.status !== "resolved").length}</h2><button className={button} disabled={!!busy} onClick={() => run("Researching open questions", async () => { await knowledge.updateMemory(project.id, { kind: "recheck" }); await refresh(); })}>Research again</button></div>{!memory.questions.length && <p className="mt-3 text-xs text-muted-foreground">Questions you keep during a meeting appear here. Index updates look for new evidence.</p>}{memory.questions.map(q => <div key={q.id} className="mt-3 border-l-2 border-border pl-3"><p className="text-sm">{q.text}</p><p className="mt-1 text-xs text-muted-foreground">{q.status === "evidence_available" ? "Possible evidence found · review needed" : q.status}</p>{refs(q.evidence)}<button className={`${button} mt-2`} disabled={!!busy} onClick={() => run("Updating question", async () => { await knowledge.updateMemory(project.id, { kind: "question", itemId: q.id, status: q.status === "resolved" ? "open" : "resolved" }); await refresh(); })}>{q.status === "resolved" ? "Reopen" : "Mark resolved"}</button></div>)}</section>
    <section className="border-t border-border pt-4"><h2 className="text-sm font-medium">Decision review</h2><button className={`${button} mt-3`} disabled={!!busy} onClick={() => run("Extracting decision drafts", async () => { const result = await knowledge.draftDecisions(project.id); setDraftNotice(`${result.drafts} new draft(s). Reviewed ${result.passagesReviewed} of ${result.totalPassages} transcript passages from your latest completed meeting. Review before approving.`); await refresh(); })}>Review latest meeting decisions</button>{draftNotice && <p role="status" className="mt-2 text-xs text-muted-foreground">{draftNotice}</p>}<p className="mt-2 text-xs text-muted-foreground">Attach sources from search to save a decision draft. Only approved decisions enter project memory.</p>{memory.decisions.map(d => <div key={d.id} className="mt-3 border-l-2 border-border pl-3"><p className="text-sm whitespace-pre-wrap">{d.text}</p><p className="mt-1 text-xs text-muted-foreground">{d.status} · {new Date(d.updatedAt).toLocaleDateString()}</p>{refs(d.evidence)}{d.status === "draft" && <div className="mt-2 flex gap-2">{["approved", "rejected"].map(status => <button className={button} key={status} disabled={!!busy} onClick={() => run("Reviewing decision", async () => { await knowledge.updateMemory(project.id, { kind: "decision", itemId: d.id, status }); await refresh(); })}>{status === "approved" ? "Approve for memory" : "Reject"}</button>)}</div>}</div>)}</section>
    <details className="border-t border-border pt-4"><summary className="text-sm cursor-pointer">Project documents</summary><p className="my-3 text-xs text-muted-foreground">Link existing uploads to this project. Unlinked documents do not enter its source index.</p><FileUpload />{resources.map(r => <label key={r.id} className="mt-3 flex items-start gap-2 text-xs"><input type="checkbox" checked={linked.includes(r.id)} disabled={!!busy} onChange={e => run("Updating project documents", async () => { await knowledge.linkDocument(project.id, r.id, e.target.checked); await refresh(); })} />{r.name}</label>)}</details>
    {source && <SourceDialog source={source} onClose={() => setSource(undefined)} />}
  </div>;
}
